package jl.fsaratings.dao;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This class was automatically generated by a tool in the Eclipse IDE to externalise
 * string properties - JL
 */
public class Messages {
	private static final String BUNDLE_NAME = "jl.fsaratings.dao.messages";

	private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

	private Messages() {
	}

	public static String getString(String key) {
		try {
			return RESOURCE_BUNDLE.getString(key);
		} catch (MissingResourceException e) {
			return '!' + key + '!';
		}
	}
}
